// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TelegramProvider } from "./context/telegram-provider";
import { MuiProvider } from "./context/mui-provider";
import { AppProvider } from "./context/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <MuiProvider>
          <TelegramProvider>
            <AppProvider>
              {children}
            </AppProvider>
          </TelegramProvider>
        </MuiProvider>
      </body>
    </html>
  );
}
